spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/cparts-store
server:
  port: 8081

